baseURL = "https://tetsu-blog.pages.dev/"
languageCode = "ja"
title = "てつblog"
ignoreFiles = ["content/templates/"]

[params]
  author = "てつ"
  description = "Antigravityを用いたHugoブログのクローン"

[permalinks]
  [permalinks.page]
    posts = "/posts/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
