baseURL = "https://tetsu-blog.pages.dev/"
languageCode = "ja"
timeZone = "Asia/Tokyo"
title = "てつblog"
ignoreFiles = ["content/templates/"]

[params]
  author = "てつ"
  description = "Antigravityを用いたHugoブログのクローン"
  favicon = "/favicon.ico"
  favicon_16x16 = "/favicon-16x16.png"
  favicon_32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"

[permalinks]
  [permalinks.page]
    posts = "/posts/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
